#!/usr/bin/env bash

GPU_IMAGE_NAME="${IMAGE_NAME}-gpu"
docker build --build-arg GPU=-gpu -f $DOCKERFILE_PATH -t $GPU_IMAGE_NAME .

docker push $GPU_IMAGE_NAME

docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME .
