name: dockerhub

on:
  release:
    types: [published]

jobs:
  docker:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux/amd64
            tag: ${{ github.event.release.tag_name }}
          - os: ubuntu-24.04-arm
            platform: linux/arm64
            tag: ${{ github.event.release.tag_name }}-arm
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.MCMICRO_USERNAME }}
          password: ${{ secrets.MCMICRO_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          push: true
          tags: labsyspharm/unmicst:${{ matrix.tag }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
